

default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: application1_development


test:
  <<: *default
  database: application1_test


#
production:
  <<: *default
  database: application1_production
  username: application1
  password: <%= ENV['APPLICATION1_DATABASE_PASSWORD'] %>
